dist: trusty
osx_image: xcode8.2
sudo: required
language: cpp

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt551-trusty'
      - ubuntu-toolchain-r-test
    packages: [
      # static analysis
      clang-3.6,
      # qt5 requirement
      #qt5-qmake, qt5-default, qtbase5-dev
      qt-latest
    ]
    

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: nightly
    - os: osx
      python: nightly

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh'); source $QT_ENV_SCRIPT; fi
#  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt purge qt4-qmake libqt4-dev; fi

script:
  - qmake --version
  - qmake -makefile NifSkope.pro
  - make -j4

notifications:
    email: false
