dist: trusty
osx_image: xcode8.2
sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - debian-sid
    packages:
    - qt5-qmake

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: nightly
    - os: osx
      python: nightly

before_install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then sudo apt purge qt4-qmake libqt4-dev; fi

script:
  - qmake --version
  - qmake -makefile NifSkope.pro
  - make -j4

notifications:
    email: false
